name: Pipeline para Deploy da aplicação no AWS



on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Compilação
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        
      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          
      - name: Compilar o projeto com Maven (sem testes)
        run: mvn clean package -DskipTests
        
      - name: Listar arquivos da pasta target
        run: ls -la target
        
      - name: Upload do artefato JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar

  test:
    name: Testes e Relatórios JaCoCo
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        
      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          
      - name: Rodar testes com cobertura JaCoCo
        run: mvn clean test
        
      - name: Upload dos relatórios de testes (Surefire)
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
          
      - name: Upload dos relatórios de cobertura (JaCoCo)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
